src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_Due__c</fullName>
        <label>Date Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Reported__c</fullName>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Work_Part__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No spare parts meet this description or name.</errorMessage>
            <filterItems>
                <field>Product2.Replacement_Part__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Request__c</fullName>
        <label>Maintenance Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Part</label>
    <nameField>
        <displayFormat>PART-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MaintenanceRequestHelper.cls
public class MaintenanceRequestHelper
{
    
    private static Case createMaintenanceRequest( Case fromMaintenanceRequest, AggregateResult aggMinCycle )
    {
        Integer minCycle    = 0;
        if( aggMinCycle != null && aggMinCycle.get( 'minCycle' ) != null )
        {            
            minCycle                = Integer.valueOf( aggMinCycle.get( 'minCycle' ) );
        }
        
        
        Case maintenanceRequest     = new Case(
            Type                = 'Routine Maintenance',
            Origin              = 'Routine Maintenance',
            Subject             = 'Routine Maintenance',
            // RecordTypeId        = '01258000000EG38',     // Field does not exist on Case object
            Status              = 'New',
            
            Vehicle__c          = fromMaintenanceRequest.Vehicle__c,
            Product__c          = fromMaintenanceRequest.Product__c,
            Date_Reported__c    = System.today(),
            Date_Due__c         = System.today().addDays( minCycle )
        );
        
        //System.debug( fromMaintenanceRequest );
        //System.debug( maintenanceRequest );
        return maintenanceRequest;
    }
    
    public static void updateWorkOrders( List<Case> closedMaintenanceRequests )
    {
        Map<Id,AggregateResult> results =  new Map<id,AggregateResult>( [SELECT Maintenance_Request__r.id, 
                                                                        Min(Equipment__r.Maintenance_Cycle__c)minCycle 
                                     									FROM Work_Part__c 
                                                                        WHERE Maintenance_Request__c in :closedMaintenanceRequests
                                                                        GROUP BY Maintenance_Request__r.id] );
        
        List<Case> newMaintenanceRequests   = new List<Case>();
        for( Case mr : closedMaintenanceRequests )
        {                     
            Case newMaintenanceRequest  = createMaintenanceRequest( mr, results.get( mr.Id ) );
            if( newMaintenanceRequest != null )
            {
            	newMaintenanceRequests.add( newMaintenanceRequest );
            }              
        }
        
        Database.insert( newMaintenanceRequests );
    }            
}